services:
  neo4j:
    image: neo4j:5.25.1
    container_name: food-tracker-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  app:
    image: eclipse-temurin:21-jre-alpine
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_ENABLED=true
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar qs-java-0.0.1-SNAPSHOT.jar
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs: