services:
  neo4j:
    image: neo4j:5.25.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data
  
  app:
    image: eclipse-temurin:21-jre-alpine
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:7687
      - SPRING_DATA_NEO4J_USERNAME=neo4j
      - SPRING_DATA_NEO4J_PASSWORD=password
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar qs-java-0.0.1-SNAPSHOT.jar
    depends_on:
      - neo4j

volumes:
  neo4j_data: